title: Shuang Guo
description: Research Scientist at Bosch
author: Shuang Guo
email: hewenbin.495@gmail.com
url: https://hewenbin.github.io
baseurl: ""

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-127130522-1
