title: Shuang Guo
description: Master Student at The Ohio State University
author: Shuang Guo
email: guo.1660@buckeyemail.osu.edu
url: https://sbj1234567892010.github.io/
baseurl: ""

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-127130522-1
